### ISSUE TITLE
types missing (e.g. uint32)

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [predictive-analytics-lab/data-science-types#130]
I am new to type-hinting, but I thought I will give it a go :)

I noticed that quite some types are missing:
https://numpy.org/doc/stable/user/basics.types.html
https://github.com/predictive-analytics-lab/data-science-types/blob/master/numpy-stubs/__init__.pyi#L43

Is there a reason for these values missing (except that it is a lot of work to migrate all at once)? I might be able to free up some time to add these in a PR if you are interested.

**Comment by olliethomas** [comment]
Hi Maarten, thanks for the question! 

Numpy is a massive library, which is great, but it posed a problem to us - if we want to have type hints for numpy, how should we do this? As you've already said, doing it all at once is a lot of work. Instead, we decided to just add type hints for the parts of numpy that we were using in our projects, and over time add new, or expand upon existing, type hints as and when this becomes useful. 

It's been really nice that other people have found this and decided to contribute too, adding type hints for the parts of numpy, pandas and matplotlib that they've been using. Because of these contributions this project has made steps towards typing these massive libraries, but there's a loooong way to go. 

I guess this is all a long way of saying, yes, please do open a PR - we always welcome contributions, and are happy to help you either get started, or help solve some of the trickier problems.

Welcome aboard!

Oliver
