### ISSUE TITLE
Will numpy stubs be removed after next numpy release?

### ISSUE THREAD

**Issue by wwuck** [predictive-analytics-lab/data-science-types#132]
Numpy has finally merged the stubs from numpy-stubs into the main numpy project.

https://github.com/numpy/numpy-stubs/pull/88
https://github.com/numpy/numpy/pull/16515

Will the numpy stubs in this project be removed when numpy 1.20.0 is released?

**Comment by olliethomas** [comment]
I think numpy-stubs has a different aim. They provide `ArrayLike`, `DtypeLike` and `_ShapeLike`, which are certainly useful, and perhaps we will have to adopt those definitions rather than our own. However, from what I can see of [what's been merged](https://github.com/numpy/numpy/tree/master/numpy/typing) there's no attribute or function support, so no support for `numpy.pi` or `numpy.random.normal(mu, sigma, samples)` for example. (I might be wrong though - please advise if this isn't the case.) These are something we provide and I think we should continue to do so.

If there are unexpected problems, we will certainly look at those.

**Comment by wwuck** [comment]
Ok, great!  I guess I will be able to continue with both side-by-side and hopefully wont create any conflicts.

**Comment by blumu** [comment]
@olliethomas  Would you consider adding an option to install the datascience-stubs without the `numpy` ones?
I spotted at least 3 forks of the repo that are just commenting out the `numpy` stubs in `setup.py`. 

On my own project I found that the typing stubs from 'numpy-stubs' provide better support than `dat-science-types`, including for `numpy.random.normal` (I am using the legacy ones at `numpy_stubs@git+https://github.com/numpy/numpy-stubs/@master#egg=numpy_stubsme`, not the ones from the forthcoming numpy 1.20)

**Comment by olliethomas** [comment]
I didn't know that this was happening. I guess we could if that's what people want? It would be useful to know more about why the 3 other users also removed numpy stubs though as we'll have to do something like [this](https://github.com/graphql-python/gql/issues/147), and it would be good to know if such a solution is beneficial to these other users as well, or if we just need to make our stubs better.

Out of interest, I've looked through the numpy-stubs repo for anything that I think could be `numpy.random.normal`, but I must be doing something wrong as I can't find it. Could you provide a link to the line? It would be good to learn what makes the better support you're experiencing.
