### ISSUE TITLE
how did  you create these?

### ISSUE THREAD

**Issue by makslevental** [predictive-analytics-lab/data-science-types#8]
are you writing these by hand or in some other way?

**Comment by thomkeh** [comment]
By hand. For example when I need a function from numpy I look at the documentation (https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html) to see which arguments the function takes and roughly what type they should have. Then I write the function signature in the type stub file.

As a starting place, we copied the code from https://github.com/numpy/numpy-stubs at the beginning but we have changed a lot since then.

**Comment by makslevental** [comment]
you might be interested in this 

https://instagram-engineering.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881

i've considered bootstrapping generating type stubs for these same libraries by using monkeytype along with their respective test suites.

**Comment by thomkeh** [comment]
I think tools like monkeytype are more for "application code" instead of "library code". The functions in the numpy library often have very complex behavior that these tools cannot capture. For example, take a look at our type signature of the `np.random.choice` function:

```python
@overload
def choice(a: _IntObj) -> _IntObj: ...
@overload
def choice(a: int, size: int) -> ndarray[int64]: ...
@overload
def choice(a: _Int, size: int) -> ndarray[_Int]: ...
@overload
def choice(
    a: List[_T], p: Union[List[_FloatObj], ndarray[_Float]] = ..., replace: bool = ...
) -> _T: ...
@overload
def choice(
    a: range, size: _IntObj, replace: bool = ..., p: Union[List[_FloatObj], ndarray[_Float]] = ...
) -> ndarray[int64]: ...
@overload
def choice(
    a: range, *, replace: bool = ..., p: Union[List[_FloatObj], ndarray[_Float]] = ...
) -> int64: ...
@overload
def choice(
    a: ndarray[_DType],
    size: _IntObj,
    replace: bool = ...,
    p: Union[List[_FloatObj], ndarray[_Float]] = ...,
) -> ndarray[_DType]: ...
@overload
def choice(
    a: ndarray[_DType], *, replace: bool = ..., p: Union[List[_FloatObj], ndarray[_Float]] = ...
) -> _DType: ...
```

We needed **8** overloads to adequately describe what this function can do. And the hardest part was working out how best to group all these types. We introduced several new union types in order to express the behavior (somewhat) nicely.

When I tried out these automated tools, I found them too "dumb" for this task unfortunately.
